### ISSUE TITLE
Invalid \escape in json anime list note

### ISSUE THREAD

**Issue by Karob2** [Jacekun/AniPy#1]
I got the error:
```
[09:25:54][trim_list]: Loading anime_2021-05-23.json into memory..
Traceback (most recent call last):
  File "D:\Tools\AniPy-1.08\main.py", line 132, in <module>
    fTrim.trim_results(PROJECT_PATH, outputAnime, outputManga)
  File "D:\Tools\AniPy-1.08\func\trim_list.py", line 49, in trim_results
    jsonAnime = json.load(F)
  File "C:\Python38\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python38\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 833 column 39 (char 19667)
```

line 833 column 39 is a `\o` in a note, part of an ascii emoji:
```
		...
		"score": 8,
		"private": "False",
		"notes": "I didn't hate the ending. \o/"
	},
```

**Comment by Jacekun** [comment]
Seems like invalid escape strings are not caught and replaced. Made a fix now, and will push it later on 'dev' branch.

EDIT: Fix is now on 'dev'

EDIT 2: Prev fix removes the strings. This is not practical, so I provided an alternate fix that allows '\' to be encoded properly (by doubling it). I will look into this more to allow ASCII Emojis to be encoded properly into the json object.

EDIT 3: Major changes committed. Hopefully, these changes fixes this error, and future errors regarding ASCII and Emojis.

**Comment by Jacekun** [comment]
'dev' branch should now have the fix
