### ISSUE TITLE
Windows [WSL2] TimeoutError: timed out

### ISSUE THREAD

**Issue by Shouri14** [Jacekun/AniPy#10]
Hi,

First of all, great program. Works very well in windows.
I prefer using Ubuntu on WSL2, and the program is timing out when attempting a connection in WSL2

<img width="1421" alt="image" src="https://github.com/Jacekun/AniPy/assets/37922572/96d07bab-778f-4c33-8cba-5befd13c8869">

Traceback:
```
Traceback (most recent call last):
  File "/mnt/f/Dev_Drive/anipy-wsl2/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/mnt/f/Dev_Drive/anipy-wsl2/venv/lib/python3.10/site-packages/urllib3/connection.py", line 454, in getresponse
    httplib_response = super().getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/f/Dev_Drive/anipy-wsl2/venv/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/mnt/f/Dev_Drive/anipy-wsl2/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/mnt/f/Dev_Drive/anipy-wsl2/venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/mnt/f/Dev_Drive/anipy-wsl2/venv/lib/python3.10/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/mnt/f/Dev_Drive/anipy-wsl2/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/mnt/f/Dev_Drive/anipy-wsl2/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 538, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/mnt/f/Dev_Drive/anipy-wsl2/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='gogoanime3.net', port=80): Read timed out. (read timeout=2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/f/Dev_Drive/anipy-wsl2/venv/bin/anipy-cli", line 8, in <module>
    sys.exit(main())
  File "/mnt/f/Dev_Drive/anipy-wsl2/venv/lib/python3.10/site-packages/anipy_cli/run_anipy_cli.py", line 8, in main
    cli.run_cli()
  File "/mnt/f/Dev_Drive/anipy-wsl2/venv/lib/python3.10/site-packages/anipy_cli/cli/cli.py", line 37, in run_cli
    cli_class(options=args, rpc_client=rpc_client).run()
  File "/mnt/f/Dev_Drive/anipy-wsl2/venv/lib/python3.10/site-packages/anipy_cli/cli/clis/base_cli.py", line 35, in run
    self.take_input()
  File "/mnt/f/Dev_Drive/anipy-wsl2/venv/lib/python3.10/site-packages/anipy_cli/cli/clis/download_cli.py", line 69, in take_input
    ep_list = ep_class.pick_range()
  File "/mnt/f/Dev_Drive/anipy-wsl2/venv/lib/python3.10/site-packages/anipy_cli/url_handler.py", line 205, in pick_range
    self.entry.latest_ep = self.get_latest()
  File "/mnt/f/Dev_Drive/anipy-wsl2/venv/lib/python3.10/site-packages/anipy_cli/url_handler.py", line 105, in get_latest
    ep_list = self._load_eps_list()
  File "/mnt/f/Dev_Drive/anipy-wsl2/venv/lib/python3.10/site-packages/anipy_cli/url_handler.py", line 43, in _load_eps_list
    r = requests.get(self.entry.category_url, timeout=2)
  File "/mnt/f/Dev_Drive/anipy-wsl2/venv/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/mnt/f/Dev_Drive/anipy-wsl2/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/mnt/f/Dev_Drive/anipy-wsl2/venv/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/mnt/f/Dev_Drive/anipy-wsl2/venv/lib/python3.10/site-packages/requests/sessions.py", line 725, in send
    history = [resp for resp in gen]
  File "/mnt/f/Dev_Drive/anipy-wsl2/venv/lib/python3.10/site-packages/requests/sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
  File "/mnt/f/Dev_Drive/anipy-wsl2/venv/lib/python3.10/site-packages/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/mnt/f/Dev_Drive/anipy-wsl2/venv/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/mnt/f/Dev_Drive/anipy-wsl2/venv/lib/python3.10/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='gogoanime3.net', port=80): Read timed out. (read timeout=2)
```

Not sure what's causing this, I installed the repo using `python3 -m pip install git+https://github.com/sdaqo/anipy-cli `
Don't think it's internet issue.

Would appreciate any help in resolving this. Thank you.

**Comment by Jacekun** [comment]
Wrong repo. I think you've mistaken my repo for this [anipy-cli script](https://github.com/sdaqo/anipy-cli).
